### ISSUE TITLE
java.lang.NoSuchFieldError: ENDER_PEARL

### ISSUE THREAD

**Issue by jaciloy** [FabioZumbi12/Sponge-RedProtect#14]
`[15:36:47] [Server thread/ERROR] [Sponge/]: Could not pass DisplaceEntityEvent$Teleport$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@93baf43
java.lang.NoSuchFieldError: ENDER_PEARL
	at br.net.fabiozumbi12.redprotect.listeners.RPPlayerListener.onPlayerTeleport(RPPlayerListener.java:707) ~[RPPlayerListener.class:?]
	at org.spongepowered.common.event.listener.TeleportListener_RPPlayerListener_onPlayerTeleport94.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.1.0-BETA-1395]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:210) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1395]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:193) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1395]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:238) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1395]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:223) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1395]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:129) [SpongeImpl.class:1.8.9-1890-4.1.0-BETA-1395]
	at org.spongepowered.common.event.SpongeCommonEventFactory.handleDisplaceEntityTeleportEvent(SpongeCommonEventFactory.java:805) [SpongeCommonEventFactory.class:1.8.9-1890-4.1.0-BETA-1395]
	at org.spongepowered.common.event.SpongeCommonEventFactory.handleDisplaceEntityTeleportEvent(SpongeCommonEventFactory.java:771) [SpongeCommonEventFactory.class:1.8.9-1890-4.1.0-BETA-1395]
	at net.minecraft.entity.Entity.setLocation(Entity.java:393) [pk.class:?]
	at net.minecraft.entity.Entity.setLocationSafely(Entity.java:349) [pk.class:?]
	at com.github.games647.flexiblelogin.ProtectionManager.protect(ProtectionManager.java:51) [ProtectionManager.class:?]
	at com.github.games647.flexiblelogin.listener.ConnectionListener.onPlayerJoin(ConnectionListener.java:72) [ConnectionListener.class:?]
	at org.spongepowered.common.event.listener.JoinListener_ConnectionListener_onPlayerJoin35.handle(Unknown Source) [?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.8.9-1890-4.1.0-BETA-1395]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:210) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1395]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:193) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1395]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:238) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1395]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:223) [SpongeModEventManager.class:1.8.9-1890-4.1.0-BETA-1395]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:129) [SpongeImpl.class:1.8.9-1890-4.1.0-BETA-1395]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:337) [lx.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:239) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:54) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:190) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289) [ek.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189) [ll.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`

**Comment by FabioZumbi12** [comment]
The API updated and removed that methods. Fixed now!

Download Again.
